### ISSUE TITLE
Vendoring breaks plugin registration

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa-istio-plugin#85]
Running `make build-plugin` inside this repository and then trying to load the .so file with an OPA executable built from the same tag as the vendored version fails:

For example:

```
root@e0bea56837b0:/opt/opa# ./opa --plugin-dir=. run --server --log-level=debug --config-file=./config.yaml
error: config error: plugin "envoy.ext_authz.grpc" not registered
```

```
root@e0bea56837b0:/opt/opa# cat config.yaml
plugins:
     envoy.ext_authz.grpc:
       addr: :9191
       query: data.envoy.authz.allow
```

As an experiment, I deleted the vendored OPA directory and tried the result and it worked so I suspect that the plugin registration is busted since it's calling the vendored runtime package. I'm not familiar enough with Go vendoring to explain _why_ this is a problem (they must be different symbols/segments under the hood?)

I think we need to revisit how vendoring is done because as it stands, the .so files are unusable.
